const countryList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas (the)",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory (the)",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands (the)",
  "Central African Republic (the)",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands (the)",
  "Colombia",
  "Comoros (the)",
  "Congo (the Democratic Republic of the)",
  "Congo (the)",
  "Cook Islands (the)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic (the)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (the) [Malvinas]",
  "Faroe Islands (the)",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories (the)",
  "Gabon",
  "Gambia (the)",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See (the)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (the Democratic People's Republic of)",
  "Korea (the Republic of)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic (the)",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands (the)",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Moldova (the Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands (the)",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger (the)",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands (the)",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines (the)",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russian Federation (the)",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan (the)",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands (the)",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates (the)",
  "United Kingdom of Great Britain and Northern Ireland (the)",
  "United States Minor Outlying Islands (the)",
  "United States of America (the)",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
];
const ethnicities = [
  "African",
  "Afrikaner",
  "Akan",
  "Albanian",
  "Amhara",
  "Arab",
  "Armenian",
  "Assyrian",
  "Azerbaijani",
  "Baloch",
  "Basque",
  "Belarusian",
  "Bengali",
  "Berber",
  "Bosniak",
  "Brazilian",
  "Breton",
  "Bulgarian",
  "Burmese",
  "Cambodian",
  "Catalan",
  "Celtic",
  "Cherokee",
  "Chinese",
  "Chuvash",
  "Coptic",
  "Cree",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "Egyptian",
  "English",
  "Estonian",
  "Faroese",
  "Fijian",
  "Filipino",
  "Finnish",
  "French",
  "Frisian",
  "Galician",
  "Georgian",
  "German",
  "Greek",
  "Greenlandic",
  "Gujarati",
  "Haitian",
  "Han Chinese",
  "Hausa",
  "Hawaiian",
  "Hazaras",
  "Hmong",
  "Hungarian",
  "Icelandic",
  "Igbo",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Italian",
  "Ijaw",
  "Japanese",
  "Javanese",
  "Jewish",
  "Kannada",
  "Kashmiri",
  "Kazakh",
  "Khmer",
  "Kikuyu",
  "Korean",
  "Kurdish",
  "Kyrgyz",
  "Lao",
  "Latvian",
  "Lebanese",
  "Lithuanian",
  "Macedonian",
  "Malay",
  "Malayali",
  "Maldivian",
  "Maltese",
  "Manx",
  "Maori",
  "Marathi",
  "Marshallese",
  "Mestizo",
  "Mexican",
  "Mongolian",
  "Montenegrin",
  "Moroccan",
  "Nepali",
  "Nigerian",
  "Norwegian",
  "Oromo",
  "Pakistani",
  "Palestinian",
  "Pashtun",
  "Persian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Quechua",
  "Romanian",
  "Russian",
  "Rusyn",
  "Sami",
  "Samoan",
  "Scottish",
  "Serbian",
  "Sindhi",
  "Sinhalese",
  "Slovak",
  "Slovene",
  "Somali",
  "Sorbian",
  "South African",
  "South Sudanese",
  "Spanish",
  "Sundanese",
  "Swahili",
  "Swedish",
  "Swiss",
  "Tajik",
  "Tamil",
  "Telugu",
  "Thai",
  "Tibetan",
  "Tigrayan",
  "Tongan",
  "Turkish",
  "Turkmen",
  "Tuvan",
  "Ukrainian",
  "Uyghur",
  "Uzbek",
  "Vietnamese",
  "Welsh",
  "Yakut",
  "Yoruba",
  "Zulu",
];
const universities = [
  "Harvard University",
  "Stanford University",
  "Massachusetts Institute of Technology (MIT)",
  "University of Cambridge",
  "University of Oxford",
  "California Institute of Technology (Caltech)",
  "University of California, Berkeley",
  "Princeton University",
  "Yale University",
  "University of Chicago",
  "Columbia University",
  "University of Tokyo",
  "ETH Zurich - Swiss Federal Institute of Technology",
  "University of Toronto",
  "National University of Singapore (NUS)",
  "University of Melbourne",
  "University of Cape Town",
];
const router = [
  "ADTRAN",
  "Aerohive Networks",
  "Alaxala Networks",
  "Allied Telesis",
  "Alcatel Lucent Enterprise",
  "Arcadyan",
  "Arris International",
  "Aruba Networks",
  "Asus",
  "Avaya",
  "AVM",
  "Barracuda Networks",
  "Brocade",
  "Billion Electric",
  "Calix",
  "Cisco Systems",
  "Control4",
  "Cradlepoint",
  "Dell",
  "Digi International",
  "DrayTek",
  "D-Link[4]",
  "ECI Telecom",
  "Enterasys",
  "Ericsson",
  "Extreme Networks",
  "FiberHome",
  "Fortinet",
  "HPE",
  "Huawei Routers",
  "Juniper Networks",
  "Linksys",
  "Meraki",
  "MikroTik",
  "Mitsubishi",
  "Motorola",
  "NEC",
  "Netgear",
  "Nokia",
  "Nokia Networks",
  "Open Mesh",
  "RAD Data Communications",
  "Ribbon Communications",
  "Ruckus Networks",
  "Ruijie Networks",
  "Sagemcom",
  "Sierra Wireless",
  "Silver Peak",
  "Technicolor",
  "Telco Systems",
  "Teltonika Networks",
  "TP-Link",
  "TRENDnet",
  "Ubiquiti",
  "USRobotics",
  "Xirrus",
  "Yamaha",
  "ZTE",
  "ZyXEL",
];
const device = [
  "AMD Athlon64",
  "AMD K5/K6/Athlon",
  "AMD x86–32_WIN32",
  "AMD x86–64_LINUX64",
  "AMD x86–64_macOS",
  "AMD x86–64_WIN64",
  "ARM10",
  "ARM11",
  "ARM64_LLP64",
  "ARM64_LP64",
  "ARM7",
  "ARM8",
  "ARM9",
  "ARM Cortex-A32",
  "ARM Cortex-A64",
  "ARM Cortex-M",
  "ARM Cortex-R",
  "Altera SoC/ARM CortexA",
  "ADSP–CM40x/ARM Cortex-M",
  "Blackfin",
  "SHARC",
  "TigerSHARC",
  "Apple ARM64",
  "Atmel AVR",
  "Atmel AVR32",
  "Atmel AVR8",
  "PowerPC32",
  68332,
  "68HC08",
  "68HC11",
  "ColdFire",
  "DSP563xx16",
  "HC(S)12",
  "MPC52xx",
  "MPC5500",
  "MPC55xx",
  "MPC5xx",
  "MPC7xxx",
  "MPC82xx",
  "MPC83xx",
  "MPC85xx",
  "MPC86xx",
  "MPC8xx",
  "S08",
  "S12x",
  "StarCore",
  "Infineon C16x, XC16x",
  "Infineon TriCore",
  "Intel x86–32_WIN32",
  ,
  "Intel x86–64_LINUX32",
  ,
  "Intel x86–64_macOS",
  ,
  "Intel x86–64_WIN64",
  "PIC18",
  "dsPIC",
  "NXP Cortex—M0/M0+",
  "NXP Cortex—M3",
  "NXP Cortex—M4",
  "Renesas M16C",
  "Renesas M32C",
  "Renesas R8C/Tiny",
  "Renesas RH850",
  "Renesas RL78",
  "Renesas RX",
  "Renesas RZ",
  "Renesas SH-2/3/4",
  "Renesas V850",
  "ST10/Super10",
  "C2000",
  "C5000",
  "C6000",
  "MSP430",
  "Stellaris Cortex—M3",
  "TMS470",
  "TMS570 Cortex—R4",
  "ASIC/FPGA",
];
const jobs = [
  "Accountant",
  "Actor/Actress",
  "Administrative Assistant",
  "Architect",
  "Artist",
  "Attorney/Lawyer",
  "Barista",
  "Bartender",
  "Chef",
  "Civil Engineer",
  "Customer Service Representative",
  "Dentist",
  "Doctor/Physician",
  "Electrician",
  "Event Planner",
  "Financial Analyst",
  "Graphic Designer",
  "Hairdresser/Stylist",
  "Human Resources Manager",
  "Interior Designer",
  "Journalist",
  "Marketing Manager",
  "Mechanical Engineer",
  "Nurse",
  "Paramedic",
  "Pharmacist",
  "Photographer",
  "Police Officer",
  "Project Manager",
  "Real Estate Agent",
  "Sales Representative",
  "Software Developer/Engineer",
  "Teacher/Educator",
  "Truck Driver",
  "Veterinarian",
  "Web Developer",
];
